### ISSUE TITLE
[RFE] make the soscleaner python code conform to the PEP 8 style guide

### ISSUE THREAD

**Issue by slashdd** [jduncan-rva/soscleaner#118]
I would suggest to make the soscleaner python code conform to the PEP 8 style guide.
pycodestyle reveals a good amount of `E501 line too long (102 > 79 characters)`

I think autopep8 can do it automatically for us.

**Comment by jduncan-rva** [comment]
yeah. i've left those in because 80 char screens really make me made on any modern laptop. 
i'm not against it. it's just annoying.
