### ISSUE TITLE
soscleaner breaks multicast addresses

### ISSUE THREAD

**Issue by bmr-cymru** [jduncan-rva/soscleaner#12]
Whether an address is multicast or not is significant diagnostic data. Currently soscleaner discards this when masking IPs:

```
-               mcastaddr: 239.255.1.1
+               mcastaddr: 10.230.230.82
```

We should map found mcast addresses to a mangled (but valid) mcast address.

**Comment by jduncan-rva** [comment]
So which mcast range should we obfuscate TO? with the refactored IP substitution it's trivial to map networks.

**Comment by bmr-cymru** [comment]
Good question.... I guess maybe one of the reserved "unusable" ranges? I'm not a big mcast expert but I guess either picking a subset of the administratively scoped (local) addresses, or even using the "unusable" group addresses (not sure this is a good idea though.. these are supposed to be *never* used on a network - I wouldn't want people to try to use sos data to create a configuration and then DOS their own switches..).

**Comment by jduncan-rva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [obfuscate multicast addresses properly](https://trello.com/c/0ipQneDK/12-obfuscate-multicast-addresses-properly)

**Comment by jduncan-rva** [comment]
I'm going to call this one fixed, with the per-network obfuscation that goes on now. It doesn't obfuscate mcast > mcast, but the range is small enough that I don't that should be the norm. Each network is a unique obfuscated network.
