### ISSUE TITLE
[RFC] Need function to change  mac address to a fake/generic one.

### ISSUE THREAD

**Issue by YoshikiRH** [jduncan-rva/soscleaner#45]
I think we may need to have a function to change MAC address to fake one.
(I believe that 52:54:00:XX:XX:XX - one which will be generated by KVM HyperVisor - is fine).

**Comment by jduncan-rva** [comment]
the problem with that is if the sosreport uses that MAC address space... maybe setting the manufacturer bits to 00:00:00 or something, and leaving the back half unique?

**Comment by jduncan-rva** [comment]
with all of the KVM VM's out there... would it still make sense to use this range?

**Comment by jduncan-rva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [obfuscate MAC addresses](https://trello.com/c/UNqcxd2k/11-obfuscate-mac-addresses)
