### ISSUE TITLE
Don't obfuscate IP addresses in installed-rpms file

### ISSUE THREAD

**Issue by vashirov** [jduncan-rva/soscleaner#60]
installed-rpms contains strings that look like IP address, but they're not.
For example, in "389-ds-base-1.3.4.0-19.el7" substring "1.3.4.0" was considered as IP address and was replaced.

**Comment by jduncan-rva** [comment]
makes sense. those false positives will have to be handled in some sort of way. Will work that through this Issue.

**Comment by jduncan-rva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Better pattern matching in installed-rpms file](https://trello.com/c/ouFnl4Jy/6-better-pattern-matching-in-installed-rpms-file)
