### ISSUE TITLE
soscleaner will crash if /tmp is filed during extraction

### ISSUE THREAD

**Issue by Thelvaen** [jduncan-rva/soscleaner#62]
If /tmp is a small partition, and if the part is filed while extracting files, soscleaner will crash during that process (that's expected), but it won't cleanup it's file after that.

**Comment by jduncan-rva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Clean up after crash if /tmp fills during extraction](https://trello.com/c/KCR9I8h6/5-clean-up-after-crash-if-tmp-fills-during-extraction)
