### ISSUE TITLE
soscleaner should probably remove informations in resolv.conf

### ISSUE THREAD

**Issue by valleedelisle** [jduncan-rva/soscleaner#65]
One of our customer has that requirement. They need to have resolv.conf to be cleaned up as well.

**Comment by jduncan-rva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Obfuscate resolv.conf](https://trello.com/c/WXpQz0fs/1-obfuscate-resolvconf)

**Comment by jduncan-rva** [comment]
using the following as a sample:

```
search localdomain redhat.com
nameserver 172.16.238.2
```

The IP is obfuscated cleanly with the 0.3.x updates, and redhat.com is obfuscated cleanly with the updates from #66 and other recent issues. 

```
>>> hline1 = 'search localdomain redhat.com'
>>> hline2 = 'nameserver 172.16.238.2'
>>> cleaner._clean_line(hline1)
'search localdomain obfuscateddomain2.com'
>>> cleaner._clean_line(hline2)
'nameserver 128.0.0.1'
```

I'll add `localdomain` manually to the hostname database, as it's the Linux default.
