### ISSUE TITLE
soscleaner does not remove all hostnames and sub domain names

### ISSUE THREAD

**Issue by skhobbs18** [jduncan-rva/soscleaner#66]
Description of problem:
SoSCleaner does not remove other hostnames from the sosreport.

Version-Release number of selected component (if applicable):
soscleaner-0.2.2-13.fc28.noarch

How reproducible:
100%

Steps to Reproduce:
1. Have hostnames in the system (either in /etc/hosts or in messages)
2. Run sosreport
3. Run soscleaner

Actual results:
$ cat etc/hosts
10.230.230.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
10.230.230.23 host1.example.com
10.230.230.113 robocop.usersys.redhat.com  

The hostname of the local system is changed to host1.  However other hostnames in /etc/hosts are not changed.  This goes for other system hostnames in other locations in the sosreport as well.

Oct 29 13:11:01 host0 NetworkManager[698]: <info>  [1540833061.8365] dhcp4 (eth0):   domain name 'hq.gsslab.rdu.redhat.com'

Expected results:
The cleaner should remove all hostnames from the sosreport that may include any sub domains of the parent hostname.

In this case the hostname of the host is:
dhcp-10-12-211-147.hq.gsslab.rdu.redhat.com

It would be nice to remove anything in the sosreport containing any domain in the redhat.com space.

**Comment by jduncan-rva** [comment]
This is a regression. Adding to 3.0

**Comment by jduncan-rva** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Not all hostnames are obfuscated](https://trello.com/c/XKloBCBf/4-not-all-hostnames-are-obfuscated)

**Comment by jduncan-rva** [comment]
@skhobbs18 this could add some performance hits, but I'm hoping some refactoring in the hostname obfuscation engine will make it a wash. working on this now.
