### ISSUE TITLE
[BUG]- Config file does not seem to accept the log level options

### ISSUE THREAD

**Issue by skhobbs18** [jduncan-rva/soscleaner#94]
**Describe the bug**
When setting debug log level in /etc/sysconfig/soscleaner the debug option is not properly set.  I have attempted this will both debug and DEBUG options.

[Default]
loglevel = DEBUG

**Expected behavior**
Expect debug logging.

**Additional context**
Setting debug on the command line still produces the debug logs.

**Comment by jduncan-rva** [comment]
with no config file present: 
```
mv /etc/sysconfig/soscleaner /etc/sysconfig/soscleaner.bak
>>> from soscleaner import SOSCleaner
>>> cleaner = SOSCleaner()
>>> cleaner.loglevel
'INFO'  # this is the default level

```
moved config file back:
```
# mv /etc/sysconfig/soscleaner.bak /etc/sysconfig/soscleaner
# grep loglevel /etc/sysconfig/soscleaner
loglevel = debug
>>> from soscleaner import SOSCleaner
>>> cleaner = SOSCleaner()
>>> cleaner.loglevel
'DEBUG'
```

so not able to replicate this one. will close for now. if you can find an example in your environment please re-open with specifics.  -- jduncan
